export const BUSINESSES_ACTIONS = {
    FETCH_BUSINESSES: 'FETCH_BUSINESSES',
    FETCH_USER_BUSINESSES: 'FETCH_USER_BUSINESSES',
    SHOW_BUSINESSES: 'SHOW_BUSINESSES',
    POST_BUSINESSES: 'POST_BUSINESSES',
    UPDATE_BUSINESS: 'UPDATE_BUSINESS',
    UPDATE_BUSINESS_STATUS: 'UPDATE_BUSINESS_STATUS',
    DELETE_BUSINESS: 'DELETE_BUSINESS',
    FETCH_BUSINESS_TYPE: 'FETCH_BUSINESS_TYPE',
    SHOW_BUSINESS_TYPE: 'SHOW_BUSINESS_TYPE'
};