export const RESOURCE_ACTIONS = {
    FETCH_RESOURCES: 'FETCH_RESOURCES',
    SHOW_RESOURCES: 'SHOW_RESOURCES',
    POST_RESOURCES: 'POST_RESOURCES',
    UPDATE_RESOURCES: 'UPDATE_RESOURCES',
    DELETE_RESOURCES: 'DELETE_RESOURCES'
}